---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bs-demo
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
---
# apiVersion: backstage.io/v1alpha1
# kind: Location
# metadata:
#   name: testing-additions
# spec:
#   type: url
#   targets:
#     - https://github.com/cedadev/rowan-backstage-service-test/blob/master/catalog-info.yaml
#     - https://github.com/djspstfc/fake-library/blob/main/catalogue-info.yaml
#     - https://github.com/cedadev/rowan-backstage-library/blob/main/catalog-info.yaml
#     - https://github.com/cedadev/backstage-template-created-repo-4/blob/master/catalog-info.yaml
# #     - https://gitlab.ceda.ac.uk/cedadev/rowan-backstage-gl-comp-testing/blob/main/catalog-info.yaml
